services:
  primary:
    image: postgres:15
    container_name: primary
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_DB: atom
    ports:
      - 5000:5432
    command: postgres

  standby-1:
    image: postgres:15
    container_name: standby-1
    shm_size: 1g
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
      PGHOST: primary
    volumes:
      - ./bin/replica-1.sh:/scripts/init.sh
    depends_on:
      - primary
    restart: always
    command: /bin/sh -c "chmod +x /scripts/init.sh && /scripts/init.sh"
    ports:
      - 5001:5432

  standby-2:
      image: postgres:15
      container_name: standby-2
      shm_size: 1g
      environment:
        PGUSER: replicator_2
        PGPASSWORD: replicator_password
        PGHOST: primary
      volumes:
        - ./bin/replica-2.sh:/scripts/init.sh
      depends_on:
        - primary
      restart: always
      command: /bin/sh -c "chmod +x /scripts/init.sh && /scripts/init.sh"
      ports:
        - 5002:5432
